# Generated by Django 4.1.4 on 2023-06-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAllocation',
            fields=[
                ('lecture_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=20)),
                ('room_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'classroom_allocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordination',
            fields=[
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'classroom_coordination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SyllabusBaseInfo',
            fields=[
                ('lecture_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=8)),
                ('day', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'syllabus_base_info',
                'managed': False,
            },
        ),
    ]
